"""initial schema

Revision ID: 5c43d263ae48
Revises: 
Create Date: 2026-04-10 20:47:42.479781

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5c43d263ae48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebay_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('ebay_item_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'ended', 'error', name='listingstatus'), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('price_aud', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ebay_listings_sku'), 'ebay_listings', ['sku'], unique=True)
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('action', sa.Enum('create', 'revise', 'end', 'image_upload', 'sync_check', name='syncaction'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ebay_item_id', sa.String(length=50), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_log_sku'), 'sync_log', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_log_sku'), table_name='sync_log')
    op.drop_table('sync_log')
    op.drop_index(op.f('ix_ebay_listings_sku'), table_name='ebay_listings')
    op.drop_table('ebay_listings')
    # ### end Alembic commands ###
